--?? 1. Script Base de Datos (Oracle 19c)
CREATE TABLE ESTUDIANTES_CONFIRMADOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100),
    PROMEDIO NUMBER(4,2),
    ESTADO VARCHAR2(20)
);

COMMIT;